export const ADD_TO_CART="ADD_TO_CART";
export const CHANGE_MESSAGE="CHANGE_MESSAGE";
export const CHANGE_MESSAGE2="CHANGE_MESSAGE2";
export const CHANGE_MESSAGE3="CHANGE_MESSAGE3";
export const DELETE_PRODUCT="DELETE_PRODUCT";
export const UPDATE_PRODUCT="UPDATE_PRODUCT";